services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=rememberizer'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: 'rememberizer:latest'
    build:
      context: .
    container_name: app
    ports:
      - '8080:8090'
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rememberizer'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=none'

volumes:
  postgres-data: